# Generated by Django 2.0.6 on 2018-06-28 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_userprofile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='pic',
            field=models.ImageField(null=True, upload_to='profilepics'),
        ),
    ]
