# Generated by Django 2.0.6 on 2018-06-29 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0004_auto_20180628_1958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(choices=[('M', 'M'), ('F', 'F'), ('X', 'X')], default='X', max_length=1),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='sugest',
            field=models.BooleanField(default=True),
        ),
    ]
