# Generated by Django 2.0.6 on 2018-06-29 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0005_auto_20180629_2227'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='pic',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(blank=True, upload_to='profilepics'),
        ),
    ]
