# Generated by Django 2.0.6 on 2018-06-29 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0006_auto_20180629_2318'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='notification',
            field=models.CharField(choices=[('P', 'Push'), ('S', 'SMS'), ('E', 'Email'), ('N', 'Non')], default='P', max_length=1),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('X', 'X')], default='X', max_length=1),
        ),
    ]
