# Generated by Django 2.0.6 on 2018-07-03 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0008_auto_20180630_0057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='follows',
            field=models.ManyToManyField(blank=True, default='', related_name='followed_by', to='register.UserProfile'),
        ),
    ]
