# Generated by Django 2.0.6 on 2018-07-03 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0009_auto_20180703_0149'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='follow_requests',
            field=models.ManyToManyField(blank=True, default='', related_name='requested_by', to='register.UserProfile'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(blank=True, default='profilepics/default.png', upload_to='profilepics'),
        ),
    ]
