# Generated by Django 2.0.6 on 2018-06-26 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('follow', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follower',
            old_name='following',
            new_name='followers',
        ),
    ]
